#!/bin/csh
#PBS -l nodes=4:ppn=12
#PBS -l walltime=99:00:00
#PBS -l arch=gpulinux
#PBS -mae 
#PBS -j oe
#PBS -k oe
#PBS -M johannes.reppin@hs.uni-hamburg.de
#PBS -N zeus_mp2
#PBS -V
cd $PBS_O_HOME
source /etc/profile.d/modules.sh
source .bashrc

cd $PBS_O_WORKDIR
##touch jobinfo.txt
##echo $PBS_O_WORKDIR >> ./jobinfo.txt
##echo $PBS_JOBID >> ./jobinfo.txt
##
##lamboot $PBS_NODEFILE
##./mpiwrap.pl -wd $PBS_O_WORKDIR
##wipe $PBS_NODEFILE
mpirun --hostfile $PBS_NODEFILE -np 48 zeusmp.x
