#!/bin/csh
#PBS -l nodes=8:ppn=6
#PBS -l walltime=99:00:00
#PBS -l arch=gpulinux
#PBS -mae 
#PBS -j oe
#PBS -M johannes.reppin@hs.uni-hamburg.de
#PBS -N test1
#PBS -V
cd $PBS_O_HOME
source /etc/profile.d/modules.sh
source .bashrc

##cd $PBS_O_WORKDIR
##touch jobinfo.txt
##echo $PBS_O_WORKDIR >> ./jobinfo.txt
##echo $PBS_JOBID >> ./jobinfo.txt
##
##lamboot $PBS_NODEFILE
##./mpiwrap.pl -wd $PBS_O_WORKDIR
##wipe $PBS_NODEFILE
mpirun -np 48  -machinefile $PBS_NODEFILE zeusmp.x
